#!/bin/sh

mkdir -p "${39}"

touch "$1"

# echo "basedir: $2" >> "$1"
echo "filename: $3" >> "$1"
echo "trans: $4" >> "$1"
echo "columns: $5" >> "$1"
echo "wlgtomicron: $6" >> "$1"
echo "vac_air: $7" >> "$1"
echo "wrange_include: $8" >> "$1"
echo "wrange_exclude: $9" >> "$1"
echo "prange_exclude: ${10}" >> "$1"
echo "output_dir: ${38}/output/" >> "$1"
echo "output_name: ${11}" >> "$1"
echo "plot_creation: none" >> "$1"
echo "plot_range: 0" >> "$1"
echo "ftol: ${12}" >> "$1"
echo "xtol: ${13}" >> "$1"
echo "list_molec: ${14}" >> "$1"
echo "fit_molec: ${15}" >> "$1"
echo "relcol: ${16}" >> "$1"
echo "pwv: ${17}" >> "$1"
echo "flux_unit: ${18}" >> "$1"
echo "fits_back: ${19}" >> "$1"
echo "tel_back: ${20}" >> "$1"
echo "fit_cont: ${21}" >> "$1"
echo "cont_n: ${22}" >> "$1"
echo "cont_const: ${23}" >> "$1"
echo "fit_wlc: ${24}" >> "$1"
echo "wlc_n: ${25}" >> "$1"
echo "wlc_const: ${26}" >> "$1"
echo "fit_res_box: ${27}" >> "$1"
echo "relres_box: ${28}" >> "$1"
echo "kernmode: ${29}" >> "$1"
echo "fit_res_gauss: ${30}" >> "$1"
echo "res_gauss: ${31}" >> "$1"
echo "fit_res_lorentz: ${32}" >> "$1"
echo "res_lorentz: ${33}" >> "$1"
echo "kernfac: ${34}" >> "$1"
echo "varkern: ${35}" >> "$1"
echo "pixsc: ${36}" >> "$1"
echo "slitw: ${37}" >> "$1"
echo "user_workdir: ${38}" >> "$1"
echo "kernel_file: ${39}" >> "$1"
echo "end" >> "$1"
